const actionTypes = {
  GET_ALL_APPLICATION: "GET_ALL_APPLICATION",
  SET_ALL_APPLICATION: "SET_ALL_APPLICATION",

  GET_SELECTED_APP: "GET_SELECTED_APP",
  SET_SELECTED_APP: "SET_SELECTED_APP",

  GET_ALL_TEMPLATE: "GET_ALL_TEMPLATE",
  SET_ALL_TEMPLATE: "SET_ALL_TEMPLATE",

  GET_ALL_NOTIFICATION: "GET_ALL_NOTIFICATION",
  SET_ALL_NOTIFICATION: "SET_ALL_NOTIFICATION",

  SET_ALL_TMP_DATA: "SET_ALL_TMP_DATA",
  SET_ALL_NOT_DATA: "SET_ALL_NOT_DATA",

  GET_ALL_REPORTS: "GET_ALL_REPORTS",
  SET_ALL_REPORTS: "SET_ALL_REPORTS",

  STATUS_UPDATE: "STATUS_UPDATE",
  STATUS_UPDATE_SUCCESS: "STATUS_UPDATE_SUCCESS",

  GET_SAMPLE_PAYLOAD: "GET_SAMPLE_PAYLOAD",
  SET_SAMPLE_PAYLOAD: "SET_SAMPLE_PAYLOAD",

  GET_ALL_NOT_TMP_DATA: "GET_ALL_NOT_TMP_DATA",
  SET_ALL_NOT_TMP_DATA: "SET_ALL_NOT_TMP_DATA",

  SET_CASH_MAP: "SET_CASH_MAP",
  ADD_NOTIFICATION: "ADD_NOTIFICATION",
  EDIT_NOTIFICATION: "EDIT_NOTIFICATION",
  POST_SUCCESS: "POST_SUCCESS",

  GET_ALL_CHANNEL: "GET_ALL_CHANNEL",
  SET_ALL_CHANNEL: "SET_ALL_CHANNEL",

  GET_CATEGORY_LIST: "GET_CATEGORY_LIST",
  SET_CATEGORY_LIST: "SET_CATEGORY_LIST",

  GET_NOTIFICATION_LIST: "GET_NOTIFICATION_LIST",
  SET_NOTIFICATION_LIST: "SET_NOTIFICATION_LIST",

  GET_TEMPLATE_DETAIL: "GET_TEMPLATE_DETAIL",
  SET_TEMPLATE_DETAIL: "SET_TEMPLATE_DETAIL",
  CLEAR_TEMPLATE_DETAIL: "CLEAR_TEMPLATE_DETAIL",

  UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",

	TOGGLE_HEADER: "TOGGLE_HEADER",
  SET_LOADER:"SET_LOADER",
  
  ADD_BREADCRUMB : "ADD_BREADCRUMB",
  REMOVE_BREADCRUMB : "REMOVE_BREADCRUMB",
  GET_BREADCRUMBS :"GET_BREADCRUMBS",
  REMOVE_ALL_BREADCRUMBS :"REMOVE_ALL_BREADCRUMBS"
};

export default actionTypes;
